name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Linux VST3
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository -y ppa:ubuntu-toolchain-r/test
        apt-get update

        # Install build dependencies
        apt-get install -y \
          build-essential \
          pkg-config \
          cmake \
          libasound2-dev \
          libjack-jackd2-dev \
          ladspa-sdk \
          libcurl4-openssl-dev \
          libfreetype6-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxext-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxrender-dev \
          libwebkit2gtk-4.0-dev \
          libglu1-mesa-dev \
          mesa-common-dev \
          libgtk-3-dev \
          libgtk2.0-dev \
          libglib2.0-dev \
          libpango1.0-dev \
          libcairo2-dev \
          libatk1.0-dev \
          libharfbuzz-dev \
          ninja-build \
          gcc-11 \
          g++-11

        # Set GCC 11 as default
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

    - name: Verify GTK Installation
      run: |
        dpkg -s libgtk-3-dev || { echo 'libgtk-3-dev is not installed'; exit 1; }
        pkg-config --cflags gtk+-3.0

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DJUCE_BUILD_EXTRAS=OFF \
          -DJUCE_ENABLE_MODULE_SOURCE_GROUPS=ON \
          -DJUCE_DISABLE_WEBKIT=1 \
          -DJUCE_WEB_BROWSER=0 \
          -DCMAKE_C_COMPILER=gcc-11 \
          -DCMAKE_CXX_COMPILER=g++-11 \
          -DCMAKE_CXX_FLAGS="`pkg-config --cflags gtk+-3.0` -I/usr/include/harfbuzz"

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Linux-VST3
        path: build/LittleLatchy_artefacts/Release/VST3/*.vst3/
