name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows VST3
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Configure CMake
      shell: bash
      run: |
        cmake -B ${{github.workspace}}/build \
          -G "Visual Studio 17 2022" \
          -A x64 \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: bash
      run: cmake --build ${{github.workspace}}/build --config Release --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C Release --output-on-failure

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Windows-VST3
        path: build/LittleLatchy_artefacts/Release/VST3/*.vst3/
